# [dzfrias/projectable's ci](https://github.com/dzfrias/projectable/blob/main/.github/workflows/ci.yml)

# code(core): set this github action name as test

name: test

# code(core): let this workflow run when branch main push or pull_request
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  APP_NAME: rcli
  RUST_BACKTRACE: 1
  RUST_LOG: trace

jobs:
  # code(core): define job test
  test:
    name: test
    # code(core): let it run on strategy.matrix.os
    # code(core): use os ubuntu-latest, windows-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # code(core): clone -> install rust -> setup cache -> build -> run test
      - name: clone repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
